[[headers]]
  for = "/images/*-*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public'''

[[headers]]
  for = "/assets/chunk.*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public'''

[[headers]]
  for = "/assets/rails-diff-*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public'''

[[headers]]
  for = "/assets/vendor-*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public'''

[[redirects]]
  from = "https://www.railsdiff.com/*"
  to = "https://railsdiff.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://railsdiff.com/*"
  to = "https://railsdiff.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
