---
name: "Deployment"

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with:
          node-version: "14.x"
      - uses: "actions/cache@v2"
      - run: "npm install"
      - run: "npm run build"

      - uses: 'netlify/actions/cli@master'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: "deploy --dir=dist --prod"
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
